package org.example.office.settings.mapper;

import org.example.office.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    int updateByPrimaryKey(User record);

    User selectUserByLoginActAndPwd(Map<String,Object> map);
    List<User> selectAllUsers();
}