package org.example.office.settings.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.id
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.teacher
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.login_act
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    private String loginAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.login_pwd
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.division
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    private String division;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.id
     *
     * @return the value of zh.id
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.id
     *
     * @param id the value for zh.id
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.teacher
     *
     * @return the value of zh.teacher
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.teacher
     *
     * @param teacher the value for zh.teacher
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.login_act
     *
     * @return the value of zh.login_act
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public String getLoginAct() {
        return loginAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.login_act
     *
     * @param loginAct the value for zh.login_act
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public void setLoginAct(String loginAct) {
        this.loginAct = loginAct == null ? null : loginAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.login_pwd
     *
     * @return the value of zh.login_pwd
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.login_pwd
     *
     * @param loginPwd the value for zh.login_pwd
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.division
     *
     * @return the value of zh.division
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.division
     *
     * @param division the value for zh.division
     *
     * @mbggenerated Sun Apr 17 15:09:47 CST 2022
     */
    public void setDivision(String division) {
        this.division = division == null ? null : division.trim();
    }
}