package org.example.office.settings.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.id
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.login_act
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    private String loginAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.login_pwd
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh.division
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    private String division;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.id
     *
     * @return the value of zh.id
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.id
     *
     * @param id the value for zh.id
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.login_act
     *
     * @return the value of zh.login_act
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public String getLoginAct() {
        return loginAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.login_act
     *
     * @param loginAct the value for zh.login_act
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public void setLoginAct(String loginAct) {
        this.loginAct = loginAct == null ? null : loginAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.login_pwd
     *
     * @return the value of zh.login_pwd
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.login_pwd
     *
     * @param loginPwd the value for zh.login_pwd
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh.division
     *
     * @return the value of zh.division
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh.division
     *
     * @param division the value for zh.division
     *
     * @mbggenerated Wed Apr 06 20:00:41 CST 2022
     */
    public void setDivision(String division) {
        this.division = division == null ? null : division.trim();
    }
}